name: Pull Request CI

on:
  pull_request:       # プルリクエストイベント全体を監視
    types: [opened, synchronize, reopened]  # 必要に応じてフィルタリング可能

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Run tests
        run: |
          echo "Running tests..."
          # 実際のテストコマンドをここに追加

      - name: Notify Slack
        if: ${{ success() }}
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: workflow,action
          custom_payload: |
            {
              attachments: [{
                color: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
                text: `成功しました`,
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.DEV_SLACK_WEBHOOK_API_URL }}

      - name: Notify Slack
        if: ${{ success() }}
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: workflow,action
          custom_payload: |
            {
              attachments: [{
                color: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
                text: `失敗しました`,
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.DEV_SLACK_WEBHOOK_API_URL }}
